name: status
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  status:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://fs11.herokuapp.com/health"
          max-attempts: 3
          retry-delay: 5s
